name: Workflow for Codecov Action
on: [push, pull_request]
jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: yarn install
        run: |
          yarn install --frozen-lockfile
      - name: yarn coverage
        uses: GabrielBB/xvfb-action@v1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          run: |
            yarn coverage
      - name: upload coverage to Codecov
        uses: codecov/codecov-action@v1.0.12
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          fail_ci_if_error: true
          run: |
            bash <(curl -s https://codecov.io/bash)
