name: Workflow for Codecov Action
on: [push, pull_request]
jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: yarn install
        run: |
          yarn install --frozen-lockfile
      - name: yarn coverage
        run: |
          yarn coverage
      - name: Upload coverage to Codecov
        uses: ./
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          uses: codecov/codecov-action@v1.0.12
          file: ./coverage.xml
          directory: ./coverage/
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
