name: Test

on: [push, pull_request]

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-10.14, windows-2019, ubuntu-18.04]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2.3.1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1.4.2
        with:
          node-version: 14

      - name: set yarn to npmjs
        run: |
          yarn config set registry https://registry.npmjs.org

      - name: yarn install
        run: |
          yarn install --frozen-lockfile

      - name: npm install
        if: ${{ failure() }}
        run: npm install

      # - uses: borales/actions-yarn@v2.3.0
      #   with:
      #     cmd: install --frozen-lockfile

      - name: yarn package-ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn package-ci

      - name: yarn lint
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn lint

      - name: yarn tsc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn tsc

      - name: yarn test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn test

      - name: yarn build-e2e
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn build-e2e

      - name: yarn test-e2e
        uses: GabrielBB/xvfb-action@v1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          run: yarn test-e2e
